### PR TITLE
show pins nearby on the root page (fixed)

### PR DESCRIPTION
**Pull request by Yaroslav-F**
The trouble was in a pins controller, fixed now.

### CODE REVIEW

**Comment by Yaroslav-F** [comment]
Yes, the problem was for users that were not logged in, I've fixed it with this commit https://github.com/Yaroslav-F/pinteresting/commit/41e2e1a00d5f3244dc70aae88ca71c7f0ea0e587

That was because current_user is nil when user is logged out, so current_user.address returned an error.

**Comment by matmenzl** [comment]
merged. now pins are not visible anymore on home

**Comment by matmenzl** [comment]
merged it. works now to create adress while creating a pin. pins are not
visible anymore on index-page though.

2015-03-13 13:08 GMT+01:00 Yaroslav notifications@github.com:

**Comment by Yaroslav-F** [comment]
That's because now we are showing not all pins on the page, but only pins that are near your location.
Your location can be changed in the account settings.

**Comment by matmenzl** [comment]
ah, awesome!

2015-03-13 16:36 GMT+01:00 Yaroslav notifications@github.com:

**Pull request merged**
